g50_set_command:
  target:
    entity:
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE
  fields:
    temperature:
      filter:
        supported_features:
          - climate.ClimateEntityFeature.TARGET_TEMPERATURE
      selector:
        number:
          min: 0
          max: 250
          step: 0.1
          mode: box
